name: 050-docker-build-workflow

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      working-directory: github-actions-course/03-app-dotnet
      run: docker build . --file Dockerfile --tag my-app-dotnet:$(date +%s)
