name: dotnet-workflow
on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:
jobs:
  build-dotnet-app:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: github-actions-course/03-app-dotnet
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
        
    
